variables:
  CDP_IMAGE: ouestfrance/cdp:latest

stages:
  - build
  - package
  - deploy

build:
  image: $CDP_IMAGE
  stage: build
  script:
    - yarn install
    - ./node_modules/gulp/bin/gulp.js html
    - npm run build-storybook
  artifacts:
    paths:
      - dist
    expire_in: 1day
  only:
    - branches
  except:
    - master
  tags:
    - int

package_review:
  image: $CDP_IMAGE
  stage: package
  script:
    - cdp docker --image-tag-branch-name --use-gitlab-registry
  dependencies:
    - build_front
    - build_server
  only:
    - branches
  except:
    - master
  tags:
    - int

deploy_review:
  image: $CDP_IMAGE
  stage: deploy
  script:
    - cdp k8s --use-gitlab-registry --namespace-project-branch-name --image-tag-branch-name --delete-labels=120 --create-default-helm
  environment:
    name: review/$CI_COMMIT_REF_NAME
  only:
    - branches
  except:
    - master
    - develop
  tags:
    - int

